MODEL_NAME='text-curie-001'
TITLE = 'AAPI Women in {topic} - The Community Service, Sisterhood, and Empowerment'
TOPIC = 'topic'
PERSON = 'person'
ASK = 'ask'
INITIATIVE = 'initiative'
SECONDARY_ASK = 'secondary-ask'
OPENING_PARAGRAPH_TEMPLATE = 'As a {person} interested in empowering AAPI women and making friends in Chicago, give 1 paragraph explaining why {topic} is relevant.'
PITCH_PARAGRAPH_TEMPLATE = 'As a {person} who is interested in {topic}, give 1 paragraph explaining why it is important support a non-profit organization.'
ASK_PARAGRAPH_TEMPLATE = 'As an engaged community member who is ready to support, give 1 paragraph telling me that I should {ask} {initiative}'
ALTERNATIVE_ASK_PARAGRAPH_TEMPLATE = 'As someone who cannot {ask} {initiative}, give 1 paragraph telling me that I should {secondary-ask} '
CHI_AWE_WEBSITE = "https://www.chi-awe.org/"
MISS_ASIAN_CHICAGO_WEBSITE = "https://www.missasianchicago.info/"
MISS_CHINESE_CHICAGO_WEBSITE = "https://www.misschinesechicago.info/"
ASIAN_FASHION_SHOW_CHICAGO_WEBSITE = "https://www.chiasian.fashion/"
ALL_CHI_AWE_WEBSITES = [CHI_AWE_WEBSITE, MISS_ASIAN_CHICAGO_WEBSITE, MISS_CHINESE_CHICAGO_WEBSITE, ASIAN_FASHION_SHOW_CHICAGO_WEBSITE]
SCRAPED_JSON = "website_text.json"
SCRAPED_TEXT = "website_text.txt"