MODEL_NAME='text-curie-001'
TITLE = 'AAPI Women in {topic} - The Community Service, Sisterhood, and Empowerment'
TOPIC = 'topic'
PERSON = 'person'
OPENING_PARAGRAPH_TEMPLATE = 'As a {person} interested in empowering AAPI women and making friends in Chicago, convince me why {topic} is important.'
SECOND_PARAGRAPH_TEMPLATE = 'As a {person} who is interested in {topic}, convince me why I should donate.'
CHI_AWE_WEBSITE = "www.chi-awe.org"
MISS_ASIAN_CHICAGO_WEBSITE = "www.missasianchicago.info"
MISS_CHINESE_CHICAGO_WEBSITE = "www.misschinesechicago.info"
ASIAN_FASHION_SHOW_CHICAGO_WEBSITE = "www.chiasian.fashion"
ALL_CHI_AWE_WEBSITES = [CHI_AWE_WEBSITE, MISS_ASIAN_CHICAGO_WEBSITE, MISS_CHINESE_CHICAGO_WEBSITE, ASIAN_FASHION_SHOW_CHICAGO_WEBSITE]